"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import sys

from setuptools import setup

from setup_ext import SetupExt

appname = "ToJpeger"
APP = ['start.py']
DATA_FILES = ["reveal_files.scpt"]
OPTIONS = {"iconfile": "icon.icns",
           "plist": {"CFBundleName": appname,
                     "CFBundleShortVersionString": "1.0.0",
                     "CFBundleVersion": "1.0.0",
                     "CFBundleIdentifier":f"com.evlosh.ToJpeger",
                     "NSHumanReadableCopyright": (
                         "Created by Evgeny Loshkarev"
                         "\nCopyright © 2024"
                         "\nAll rights reserved.")}}


if __name__ == "__main__":
    sys.argv.append("py2app")

    setup(
        app=APP,
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app'],
    )

    SetupExt(py_ver="3.11", appname=appname)